#!/usr/bin/env python3
# vim: shiftwidth=4:tabstop=4:expandtab
############################################################################
#
# pyobd
#
# Copyright 2004 Donour Sizemore (donour@uchicago.edu)
# Copyright 2009 Secons Ltd. (www.obdtester.com)
# Copyright 2019 Brian LePage (github.com/beardedone55/)
#
# This file is part of pyOBD.
#
# pyOBD is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# pyOBD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pyOBD; if not, see https://www.gnu.org/licenses/.
############################################################################

from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

import obd_io #OBD2 funcs
import os #os.environ

import threading
import sys
import serial
from serial.tools import list_ports
import platform
import time
import configparser #safe application configuration
import webbrowser #open browser from python

from obd2_codes import pcodes
from obd2_codes import ptest

ID_ABOUT  = 101
ID_EXIT   = 110
ID_CONFIG = 500
ID_CLEAR  = 501
ID_GETC   = 502
ID_RESET  = 503
ID_LOOK   = 504
ALL_ON    = 505
ALL_OFF   = 506

ID_DISCONNECT = 507
ID_HELP_ABOUT = 508
ID_HELP_VISIT = 509
ID_HELP_ORDER = 510

class MyApp(QApplication):

    StatusEvent = pyqtSignal(list)
    ResultEvent = pyqtSignal(list)
    DebugEvent = pyqtSignal(int,str)
    TestEvent = pyqtSignal(list)
    DTCEvent = pyqtSignal(list)
    DTCClearEvent = pyqtSignal(int)

    def __init__(self, myArgs):
        super().__init__(myArgs)
        self.OnInit()

    # A listctrl which auto-resizes the column boxes to fill
    # removed style for now
    class MyListCtrl(QTableWidget):
        def __init__(self, sortable=True):
            super().__init__()
            self.horizontalHeader().setStretchLastSection(True)
            self.verticalHeader().hide()
            self.setSelectionBehavior(QAbstractItemView.SelectRows)
            self.sortable = sortable

        def addTableRow(self, rowSize, data, bold=False, italic=False, alignment=Qt.AlignLeft):
            newRow = self.rowCount()
            self.insertRow(newRow)
            #loopcnt = rowSize if rowSize <= len(data) else len(data)
            #Truncate data to length of table row and populate row
            for i, cellData in enumerate(data[:rowSize]):
                cellData = QTableWidgetItem(cellData)
                cellData.setFlags(cellData.flags() & ~Qt.ItemIsEditable) #Make item uneditable
                cellData.setTextAlignment(alignment | Qt.AlignVCenter)
                font = cellData.font()
                font.setBold(bold)
                font.setItalic(italic)
                cellData.setFont(font)
                self.setItem(newRow, i, cellData)

            if rowSize > len(data):
                self.setSpan(newRow, len(data)-1, 1, rowSize - (len(data)-1))

        def setColumnCount(self, columns):
            super().setColumnCount(columns)
            if self.sortable:
                self.horizontalHeader().sectionClicked.connect(self.sortMyList)

        def sortMyList(self, column):
            header = self.horizontalHeader()
            if not header.isSortIndicatorShown():
                header.setSortIndicatorShown(True)

            self.sortItems(column, header.sortIndicatorOrder())

    #Add a Widget to a panel with a layout and return the Panel
    class MyPanel(QWidget):
        def __init__(self, widget):
            super().__init__()
            layout = QVBoxLayout()
            layout.addWidget(widget)
            self.setLayout(layout)

    class MyNumberInput(QLineEdit):
        def __init__(self, defaultText='', width=20):
            super().__init__(defaultText)
            self.setFixedWidth(width)
            validator = QIntValidator()
            validator.setBottom(0)
            self.setValidator(validator)

    class sensorProducer(threading.Thread):
        def __init__(self, _notify_window,portName,baudrate,SERTIMEOUT,RECONNATTEMPTS,_nb):
            from queue import Queue
            self.portName = portName
            self.baudrate = baudrate
            self.RECONNATTEMPTS=RECONNATTEMPTS
            self.SERTIMEOUT=SERTIMEOUT
            self.port = None
            self._notify_window=_notify_window
            self._nb=_nb
            self.active = []
            super().__init__ ()

        def initCommunication(self):
            self.port = obd_io.OBDPort(self.portName,self.baudrate,self._notify_window,self.SERTIMEOUT,self.RECONNATTEMPTS)

            if self.port.State==0: #Cant open serial port
                return None

            self.active   = []

            self.active.append(0); #PID 0 is always supported

            self._notify_window.ResultEvent.emit([0,0,""])
            self._notify_window.DebugEvent.emit(1,"Communication initialized...")

            if len(self.port.ecu_addresses) > 0:
                ecu = self.port.ecu_addresses[0]
                supp = self.port.get_supported(ecu) #read supported mode $01
                                                    #PIDS of 1st ECU that responds
                for i, supported in enumerate(supp,1):
                    self.active.append(0)
                    if supported == "1": #Unhide Row if supported
                        self._notify_window.ResultEvent.emit([i,0,""])
                        self._notify_window.sensors.setRowHidden(i,False)
                    else:
                        self._notify_window.sensors.setRowHidden(i,True)
            return "OK"

        def run(self):
            self._notify_window.StatusEvent.emit([0,1,"Connecting...."])
            self.initCommunication()
            if self.port.State==0: #cant connect, exit thread
                self.stop()
                self._notify_window.StatusEvent.emit([666]) #signal apl, that communication was disconnected
                self._notify_window.StatusEvent.emit([0,1,"Error. Cannot connect..."])
                return None

            self._notify_window.StatusEvent.emit([0,1,"Connected"])
            self._notify_window.StatusEvent.emit([2,1,self.port.ELMver])
            self._notify_window.StatusEvent.emit([1,1,self.port.protocol])
            prevstate=-1
            curstate=-1

            if len(self.port.ecu_addresses) > 0:
                ecu = self.port.ecu_addresses[0]
            else:
                ecu = None

            while self._notify_window.ThreadControl!=666 and ecu is not None:
                prevstate=curstate
                curstate=self._nb.currentIndex()
                if curstate==1: #show tests tab
                    results=self.port.get_tests_MIL()
                    for i,result in enumerate(results):
                        self._notify_window.TestEvent.emit([i,1,result])

                elif curstate==2 and ecu is not None: #show sensor tab
                    for i,active in enumerate(self.active[3:],3):
                        if active:
                            s = self.port.sensor(i,ecu)
                            self._notify_window.ResultEvent.emit([i,2,"%s (%s)" % (s[1], s[2])])
                        if self._notify_window.ThreadControl==666:
                            break
                else:
                    pass
            self.stop()

        def off(self, id):
            if id >= 0 and id < len(self.active):
                self.active[id] = 0
            else:
                debug("Invalid sensor id")
        def on(self, id):
            if id >= 0 and id < len(self.active):
                self.active[id] = 1
            else:
                debug("Invalid sensor id")

        def all_off(self):
            self.active = [0] * len(self.active)

        def all_on(self):
            self.active = [1] * len(self.active)

        def stop(self):
            if self.port != None: #if stop is called before any connection port is not defined (and not connected )
                self.port.close()
            self._notify_window.StatusEvent.emit([0,1,"Disconnected"])
            self._notify_window.StatusEvent.emit([2,1,"----"])

  #class producer end

    def sensor_control_on(self): #after connection enable few buttons
        self.configAction.setEnabled(False)
        self.connectAction.setEnabled(False)
        self.disconnectAction.setEnabled(True)
        self.getDTCAction.setEnabled(True)
        self.clearDTCAction.setEnabled(True)
        self.GetDTCButton.setEnabled(True)
        self.ClearDTCButton.setEnabled(True)

        def sensor_toggle(row, col):
            if row < len(self.senprod.active):
                state = self.senprod.active[row]
            else:
                return

            if   state == 0:
                self.sensors.item(row,0).setText("X")
                self.senprod.on(row)
            elif state == 1:
                self.senprod.off(row)
                self.sensors.item(row,0).setText("")
                self.sensors.item(row,2).setText('-------')
            else:
                debug("Incorrect sensor state")

        self.sensors.cellClicked.connect(sensor_toggle)

    def sensor_control_off(self): #after disconnect disable fer buttons
        self.getDTCAction.setEnabled(False)
        self.clearDTCAction.setEnabled(False)
        self.configAction.setEnabled(True)
        self.connectAction.setEnabled(True)
        self.disconnectAction.setEnabled(False)
        self.GetDTCButton.setEnabled(False)
        self.ClearDTCButton.setEnabled(False)

    def build_sensor_page(self):
        self.sensors = self.MyListCtrl()
        self.sensors.setColumnCount(3)
        self.sensors.setHorizontalHeaderLabels(['Active','Sensor','Value'])
        self.sensors.setColumnWidth(0,70)
        self.sensors.setColumnWidth(1,250)

        for i,obd_sensor in enumerate(obd_io.obd_sensors.SENSORS):
            s = obd_sensor.name
            self.sensors.addTableRow(3, ['', s, ''])
            self.sensors.item(i,1).setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)
            self.sensors.item(i,0).setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
            self.sensors.setRowHidden(i, True)

        sensorPage = self.MyPanel(self.sensors)
        self.nb.addTab(sensorPage, "Sensors")

    def build_DTC_page(self):
        self.DTCpanel = QWidget()
        self.GetDTCButton  = QPushButton('Get DTC')
        self.ClearDTCButton = QPushButton('Clear DTC')

        panelLayout = QGridLayout()
        panelLayout.addWidget(self.GetDTCButton,0,0)
        panelLayout.addWidget(self.ClearDTCButton,0,1)

        #bind functions to button click action
        self.GetDTCButton.clicked.connect(self.GetDTC)
        self.ClearDTCButton.clicked.connect(self.QueryClear)

        self.dtc = self.MyListCtrl()

        self.dtc.setColumnCount(3)
        self.dtc.setHorizontalHeaderLabels(['Code','Status','Trouble Code'])
        self.dtc.setColumnWidth(0,100)
        self.dtc.setColumnWidth(1,100)
        panelLayout.addWidget(self.dtc,1,0,1,2)
        self.DTCpanel.setLayout(panelLayout)

        self.nb.addTab(self.DTCpanel, "DTC")

    def TraceDebug(self,level,msg):
        if self.DEBUGLEVEL<=level:
            self.trace.addTableRow(2, [str(level),msg])

    def OnInit(self):
        self.ThreadControl = 0 #say thread what to do
        self.COMPORT = 0
        self.BAUDRATE = 0
        self.senprod = None
        self.DEBUGLEVEL = 0 #debug everthing

        def CreateMenuItem(ItemName, ToolTipText, ItemTrigger):
            menuItemAction = QAction(ItemName)
            menuItemAction.setStatusTip(ToolTipText)
            menuItemAction.triggered.connect(ItemTrigger)
            return menuItemAction


        #read settings from file
        self.config = configparser.RawConfigParser()

        #print platform.system()
        #print platform.mac_ver()[]

        if "OS" in os.environ.keys(): #runnig under windows
            self.configfilepath="pyobd.ini"
        else:
            self.configfilepath=os.environ['HOME']+'/.pyobdrc'
        if self.config.read(self.configfilepath)==[]:
            self.COMPORT="/dev/ttyACM0"
            self.RECONNATTEMPTS=5
            self.SERTIMEOUT=5
            self.BAUDRATE=9600
        else:
            self.COMPORT=self.config.get("pyOBD","COMPORT")
            self.BAUDRATE=self.config.get("pyOBD","BAUDRATE")
            self.RECONNATTEMPTS=self.config.getint("pyOBD","RECONNATTEMPTS")
            self.SERTIMEOUT=self.config.getint("pyOBD","SERTIMEOUT")

        frame = QMainWindow()
        frame.setWindowTitle('pyOBD-II')
        self.frame=frame

        self.ResultEvent.connect(self.OnResult)
        self.DebugEvent.connect(self.OnDebug)
        self.DTCEvent.connect(self.OnDtc)
        self.DTCClearEvent.connect(self.OnDtcClear)
        self.StatusEvent.connect(self.OnStatus)
        self.TestEvent.connect(self.OnTests)

        # Main notebook frames

        self.nb = QTabWidget(frame)
        self.frame.setCentralWidget(self.MyPanel(self.nb))

        self.status = self.MyListCtrl()
        self.status.setColumnCount(2)
        self.status.setHorizontalHeaderLabels(['Description','Value'])
        self.status.setColumnWidth(0,100)
        self.status.addTableRow(2, ['Link State', 'Disconnected'])
        self.status.addTableRow(2, ['Protocol', '---'])
        self.status.addTableRow(2, ['Cable Version', '---'])
        self.status.addTableRow(2, ['COM Port', self.COMPORT])

        statusPanel  = self.MyPanel(self.status)
        self.nb.addTab(statusPanel, "Status")

        self.OBDTests = self.MyListCtrl()
        self.OBDTests.setColumnCount(2)
        self.OBDTests.setHorizontalHeaderLabels(['Description','Value'])
        self.OBDTests.setColumnWidth(0,200)

        OBDTestPanel = self.MyPanel(self.OBDTests)
        self.nb.addTab(OBDTestPanel, "Tests")

        for i in ptest: #fill MODE 1 PID 1 test description
            self.OBDTests.addTableRow(2, [i,'---'])

        self.build_sensor_page()

        self.build_DTC_page()

        self.trace = self.MyListCtrl()
        self.trace.setColumnCount(2)
        self.trace.setHorizontalHeaderLabels(['Level','Message'])
        self.trace.setColumnWidth(0,40)

        tracePanel = self.MyPanel(self.trace)
        self.nb.addTab(tracePanel, "Trace")

        self.TraceDebug(1,"Application started")

        self.frame.statusBar()

        # Creating the menubar.
        self.menuBar = self.frame.menuBar()
        self.filemenu = self.menuBar.addMenu("&File") # Adding the "filemenu" to the MenuBar
        self.settingmenu = self.menuBar.addMenu("&OBD-II")
        self.dtcmenu = self.menuBar.addMenu("&Trouble codes")
        self.helpmenu = self.menuBar.addMenu("&Help")

        # Setting up the menu.

        self.exitAction = CreateMenuItem("E&xit"," Terminate the program", self.OnExit)
        self.filemenu.addAction(self.exitAction)
        self.aboutToQuit.connect(self.exitCleanup)

        self.configAction = CreateMenuItem("Configure"," Configure pyOBD",self.Configure)
        self.connectAction = CreateMenuItem("Connect"," Reopen and connect to device",self.OpenPort)
        self.disconnectAction = CreateMenuItem("Disconnect","Close connection to device",self.OnDisconnect)
        self.settingmenu.addAction(self.configAction)
        self.settingmenu.addAction(self.connectAction)
        self.settingmenu.addAction(self.disconnectAction)

        # tady toto nastavi automaticky tab DTC a provede akci
        self.getDTCAction = CreateMenuItem("Get DTCs",   " Get DTC Codes", self.GetDTC)
        self.clearDTCAction = CreateMenuItem("Clear DTC",  " Clear DTC Codes", self.QueryClear)
        self.codeLookupAction = CreateMenuItem("Code Lookup"," Lookup DTC Codes", self.CodeLookup)
        #self.testDTCAction = CreateMenuItem("Test DTC"," Test DTCs", self.onTestDTC)
        self.dtcmenu.addAction(self.getDTCAction)
        self.dtcmenu.addAction(self.clearDTCAction)
        self.dtcmenu.addAction(self.codeLookupAction)
        #self.dtcmenu.addAction(self.testDTCAction)

        self.aboutAction = CreateMenuItem("About this program","",self.OnHelpAbout)
        self.visitAction = CreateMenuItem("Visit program homepage","",self.OnHelpVisit)
        self.orderAction = CreateMenuItem("Order OBD-II interface","",self.OnHelpOrder)
        self.helpmenu.addAction(self.aboutAction)
        self.helpmenu.addAction(self.visitAction)
        self.helpmenu.addAction(self.orderAction)

        frame.show()
        frame.resize(520,400)
        self.sensor_control_off()

        return True

    def OnHelpVisit(self):
        webbrowser.open("http://www.obdtester.com/pyobd")

    def OnHelpOrder(self):
        webbrowser.open("http://www.obdtester.com/order")

    def OnHelpAbout(self): #todo about box
        Text = """<p>PyOBD is an automotive OBD2 diagnostic application that works with ELM23x cables.</p>

<p>(C) 2018-2019 Brian LePage<br>
(C) 2008-2009 SeCons Ltd.<br>
(C) 2004 Charles Donour Sizemore</p>

<p><a href='http://www.obdtester.com/'>http://www.obdtester.com/</a><br>
<a href='http://www.secons.com/'>http://www.secons.com/</a><br>
<a href='https://github.com/beardedone55/'>https://github.com/beardedone55/</a></p>

<p>PyOBD is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any later version.</p>

<p>PyOBD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.</p>

<p>You should have received a copy of the GNU General Public License along with PyOBD; if not, see <a href='https://www.gnu.org/licenses/'>https://www.gnu.org/licenses/.</a></p>
"""
        HelpAboutDlg = QMessageBox(QMessageBox.Information, 'About', Text, QMessageBox.Ok, self.frame)
        HelpAboutDlg.setTextFormat(Qt.RichText)
        HelpAboutDlg.exec()

    def OnResult(self,event):
        self.sensors.item(event[0], event[1]).setText(event[2])

    def OnStatus(self,event):
        if event[0] == 666: #signal, that connection falied
            self.sensor_control_off()
        else:
            self.status.item(event[0],event[1]).setText(event[2])

    def OnTests(self,event):
        self.OBDTests.addTableRow(3, event)

    def OnDebug(self, level, msg):
        self.TraceDebug(level, msg)

    def OnDtcClear(self, event):
        if event == 0:
            self.dtc.setRowCount(0)
        else:
            self.DebugEvent.emit(1,'Unexpected OnDtcClear -> %d' % event)

    def OnDtc(self,event):
        if len(event) == 1:
            alignment = Qt.AlignHCenter
            bold = True
        else:
            alignment = Qt.AlignLeft
            bold = False
        self.dtc.addTableRow(3, event, bold=bold, alignment=alignment)

    def OnDisconnect(self): #disconnect connection to ECU
        self.ThreadControl=666
        self.sensor_control_off()

    def OpenPort(self):
        if self.senprod: # signal current producers to finish
            self.senprod.stop()
        self.ThreadControl = 0
        self.senprod = self.sensorProducer(self,self.COMPORT,self.BAUDRATE, self.SERTIMEOUT,self.RECONNATTEMPTS,self.nb)
        self.senprod.start()

        self.sensor_control_on()

    def onTestDTC(self):
        self.DTCClearEvent.emit(0) #clear list
        self.DTCEvent.emit(['DTCs from Fake ECU'])
        self.DTCEvent.emit(['P0001', 'Active', 'Test DTC'])

    def GetDTC(self):
        self.DTCClearEvent.emit(0) #clear list
        DTCCodes=self.senprod.port.get_dtc()

        if DTCCodes is None: #Communication Issue
            self.OnDisconnect()

        for ecu in DTCCodes:
            self.DTCEvent.emit(['DTCs from ECU%d' % self.senprod.port.getEcuNum(ecu)])
            if len(DTCCodes[ecu]) == 0:
                self.DTCEvent.emit(["No DTC codes (codes cleared)"])
            for code in DTCCodes[ecu]:
                self.DTCEvent.emit([code[1],code[0],pcodes[code[1]]])

        self.nb.setCurrentWidget(self.DTCpanel.parentWidget())

    def CodeLookup(self):
        id = 0
        diag = QDialog(self.frame)
        diag.setWindowTitle('Diagnostic Trouble Codes')

        tree = QTreeWidget(diag)

        root = QTreeWidgetItem(tree)
        root.setText(0,"Code Reference")
        proot = root; # tree.AppendItem(root,"Powertrain (P) Codes")
        codes = sorted(pcodes.keys())
        group = ''
        for c in codes:
            if c[:3] != group:
                group_root = QTreeWidgetItem(proot)
                group_root.setText(0,c[:3]+"XX")
                proot.addChild(group_root)
                group = c[:3]
            leaf = QTreeWidgetItem(group_root)
            leaf.setText(0,c)
            group_root.addChild(leaf)
            codeText = QTreeWidgetItem(leaf)
            codeText.setText(0,pcodes[c])
            leaf.addChild(codeText)

        layout = QHBoxLayout(diag)
        layout.addWidget(tree)
        tree.header().hide()
        diag.setLayout(layout)
        diag.resize(400,500)
        diag.show()


    def QueryClear(self):
        id = 0
        diag = QMessageBox(QMessageBox.Question, 'Clear DTC?', \
            'Are you sure you wish to clear all DTC codes and freeze frame data?',\
            QMessageBox.Yes | QMessageBox.No, self.frame)

        r  = diag.exec()
        if r == QMessageBox.Yes:
            self.ClearDTC()

    def ClearDTC(self):
        self.senprod.port.clear_dtc()
        self.DTCClearEvent.emit(0) #clear list
        self.nb.setCurrentWidget(self.DTCpanel.parentWidget())


    def scanSerial(self):
        """Scan for available ports. Return a list of serial names"""
        available = []
        for portItem in serial.tools.list_ports.comports():
            available.append(portItem.device)
        return available

    def Configure(self):
        id = 0
        diag = QDialog(self.frame)
        diag.setWindowTitle("Configure")
        sizer = QFormLayout()

        ports = self.scanSerial()
        comportDropdown = QComboBox()
        comportDropdown.addItems(ports)
        sizer.addRow('Choose Serial Port: ', comportDropdown)

        #baudrates = ['9600', '19200', '28800', '38400', '48000', '115200']
        baudrates = [ ]
        baudrateDropdown = QComboBox()
        baudrateDropdown.addItems(baudrates)
        sizer.addRow('Choose Baud Rate: ', baudrateDropdown)

        #timeOut input control
        timeoutCtrl = self.MyNumberInput(str(self.SERTIMEOUT))
        sizer.addRow('Timeout:', timeoutCtrl)

        #reconnect attempt input control
        reconnectCtrl = self.MyNumberInput(str(self.RECONNATTEMPTS))
        sizer.addRow('Reconnect attempts:', reconnectCtrl)

        #set actual serial port choice
        if (self.COMPORT != 0) and (self.COMPORT in ports):
            comportDropdown.setCurrentIndex(ports.index(self.COMPORT))
        else:
            comportDropdown.setCurrentIndex(0)

        if comportDropdown.currentIndex() >= 0:
            for rate in serial.Serial(ports[comportDropdown.currentIndex()]).BAUDRATES:
                if rate >=9600 and rate <=115200:
                    baudrates.append(str(rate))

            baudrateDropdown.addItems(baudrates)

            if (self.BAUDRATE != 0) and (self.BAUDRATE in baudrates):
                baudrateDropdown.setCurrentIndex(baudrates.index(self.BAUDRATE))
            else:
                baudrateDropdown.setCurrentIndex(baudrates.index('38400'))

        okButton = QPushButton('OK')
        cancelButton = QPushButton('Cancel')
        buttonLayout = QHBoxLayout()
        buttonLayout.addWidget(okButton)
        buttonLayout.addWidget(cancelButton)
        okButton.clicked.connect(diag.accept)
        cancelButton.clicked.connect(diag.reject)
        sizer.addRow(buttonLayout)
        diag.setLayout(sizer)

        r  = diag.exec()

        if r == QDialog.Accepted and comportDropdown.currentIndex() >=0 and baudrateDropdown.currentIndex() >=0:

            #create section
            if self.config.sections()==[]:
                self.config.add_section("pyOBD")
            #set and save COMPORT
            self.COMPORT = ports[comportDropdown.currentIndex()]
            self.config.set("pyOBD","COMPORT",self.COMPORT)

            self.BAUDRATE = baudrates[baudrateDropdown.currentIndex()]
            self.config.set("pyOBD","BAUDRATE",self.BAUDRATE)

            #set and save SERTIMEOUT
            #If user enters a blank, it will remain unchanged
            try:
                self.SERTIMEOUT = int(timeoutCtrl.text())
            except:
                pass

            self.config.set("pyOBD","SERTIMEOUT",self.SERTIMEOUT)
            self.status.item(3,1).setText(self.COMPORT);

            #set and save RECONNATTEMPTS
            #If user enters a blank, it will remain unchanged
            try:
                self.RECONNATTEMPTS = int(reconnectCtrl.text())
            except ValueError:
                pass

            self.config.set("pyOBD","RECONNATTEMPTS",self.RECONNATTEMPTS)

            #write configuration to cfg file
            self.config.write(open(self.configfilepath, 'w'))

    def exitCleanup(self):
        self.ThreadControl=666

    def OnExit(self):
        self.quit()

app = MyApp(sys.argv)
sys.exit(app.exec_())
