#!/usr/bin/env python3
# vim: shiftwidth=4:tabstop=4:expandtab
###########################################################
#
# pyobd
#
# Copyright (C) 2019 Brian LePage (github.com/beardedone55)
#
# This make file builds and packages pyobd
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to:
#
#     Free Software Foundation, Inc.
#     51 Franklin Street, Fifth Floor
#     Boston, MA  02110-1301, USA.
#
###########################################################

import sys
from pyobd_beardedone55 import pyobdGUI

app = pyobdGUI.MyApp(sys.argv)
sys.exit(app.exec_())
